server:
  port: 8003
  
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/panel-management-db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            globally_quoted_identifiers: true
            dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
   application:
     name: panel-management-service
     
   mail:
    host: smtp.gmail.com
    username: prateekzensar@gmail.com
    password: uavoirxcxxerdzyo
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
     
   jackson :
     serialization :
        fail-on-empty-beans : false
        
springdoc:
    swagger-ui:
      path: /myswaggerui
